force-app/main/default/objects/CampaignMetric__c/CampaignMetric__c.object-meta.xml
<CustomObject>
    <label>Campaign Metric</label>
    <pluralLabel>Campaign Metrics</pluralLabel>
    <nameField>
        <label>Campaign Metric Number</label>
        <type>AutoNumber</type>
        <displayFormat>CA-{0000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignMetric__c/fields/CampaignRequest__c.field-meta.xml
<CustomField>
    <fullName>CampaignRequest__c</fullName>
    <label>Campaign Request</label>
    <type>MasterDetail</type>
    <referenceTo>CampaignRequest__c</referenceTo>
    <relationshipName>CampaignRequests</relationshipName>
</CustomField>

force-app/main/default/objects/CampaignMetric__c/fields/Clicks__c.field-meta.xml
<CustomField>
    <fullName>Clicks__c</fullName>
    <label>Clicks</label>
    <type>Number</type>
    <precision>10</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/CampaignMetric__c/fields/Impressions__c.field-meta.xml
<CustomField>
    <fullName>Impressions__c</fullName>
    <label>Impressions</label>
    <type>Number</type>
    <precision>10</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/CampaignRequest__c/CampaignRequest__c.object-meta.xml
<CustomObject>
    <label>Campaign Request</label>
    <pluralLabel>Campaign Requests</pluralLabel>
    <nameField>
        <label>Campaign Request Number</label>
        <type>AutoNumber</type>
        <displayFormat>CA-{0000}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CampaignMetricsBatch.cls
public class CampaignMetricsBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, CampaignRequest__c, Impressions__c, Clicks__c FROM CampaignMetric__c]);
    }

    public void execute(Database.BatchableContext bc, List<CampaignMetric__c> scope) {
        for (CampaignMetric__c m : scope) {
            if (m.Impressions__c != null && m.Impressions__c > 0) {
                m.Conversions__c = m.Clicks__c;
            }
        }
        update scope;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('CampaignMetricsBatch complete');
    }
}