force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <pluralLabel>Vendors</pluralLabel>
    <nameField>
        <label>Vendor Number</label>
        <type>AutoNumber</type>
        <displayFormat>VE-{0000}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VendorContract__c/VendorContract__c.object-meta.xml
<CustomObject>
    <label>Vendor Contract</label>
    <pluralLabel>Vendor Contracts</pluralLabel>
    <nameField>
        <label>Vendor Contract Number</label>
        <type>AutoNumber</type>
        <displayFormat>VE-{0000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VendorContract__c/fields/Contract_Value__c.field-meta.xml
<CustomField>
    <fullName>Contract_Value__c</fullName>
    <label>Contract Value</label>
    <type>Currency</type>
    <precision>16</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/VendorContract__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <type>MasterDetail</type>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipName>Vendors</relationshipName>
</CustomField>

force-app/main/default/classes/ContractExpiryBatch.cls
public class ContractExpiryBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, Vendor__c, Contract_Value__c, End_Date__c FROM VendorContract__c]);
    }

    public void execute(Database.BatchableContext bc, List<VendorContract__c> scope) {
        ContractRenewalService.flagUpcomingExpiry(scope);
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('ContractExpiryBatch complete');
    }
}